"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";
import SideBar from "@/components/layout/SideBar";
import NavBar from "@/components/layout/NavBar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Better Player Win",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sideBarShow, setSideBarShow] = useState<boolean>(true);
  return (
    <html lang="en">
      <body
        className={`${
          inter.className
        } h-full min-h-screen bg-primary-normal text-primary-light ${
          sideBarShow ? "expanded-pages" : "shrinked-pages"
        } pt-[80px]`}
      >
        <NavBar sidebarShow={sideBarShow} setSidebarShow={setSideBarShow} />
        <SideBar sidebarShow={sideBarShow} setSidebarShow={setSideBarShow} />
        {children}
      </body>
    </html>
  );
}
